package io.fluxor.sdk.tool;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonNode;
import io.fluxor.sdk.internal.Json;
import io.fluxor.sdk.provider.ToolSpec;
import io.fluxor.sdk.schema.SchemaExtractor;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Scans Java objects for {@link FluxorTool}-annotated methods and exposes them to the
 * runtime. Parameter schemas are generated by reusing {@link SchemaExtractor}; a call is
 * dispatched by binding the model's JSON arguments back to the method parameters (by name)
 * and invoking it reflectively.
 *
 * <p>Tool methods may return any value (serialized to JSON) or a {@link CompletableFuture}
 * (awaited and then serialized), keeping the whole pipeline non-blocking.
 *
 * <p>All argument binding and reflective invocation is offloaded to a dedicated
 * {@link ExecutorService} (the <em>tool executor</em>) so that blocking or CPU-heavy tool
 * methods never steal threads from the provider's I/O completion pool. The default pool
 * uses daemon threads named {@code fluxor-tool-N} so a bare {@code new ToolRegistry()} in
 * tests never blocks JVM exit.
 *
 * <p>When a {@code ToolRegistry} is constructed without an externally supplied executor it
 * owns the executor and shuts it down in {@link #shutdown()}. When an executor is injected
 * via {@link #ToolRegistry(SchemaExtractor, ExecutorService)} the caller retains ownership
 * and {@link #shutdown()} is a no-op for that executor.
 */
public final class ToolRegistry {

    /**
     * Thread factory for the default daemon tool-executor pool.
     * Threads are named {@code fluxor-tool-1}, {@code fluxor-tool-2}, etc.
     */
    private static final class FluxorToolThreadFactory implements ThreadFactory {

        private final AtomicInteger counter = new AtomicInteger(0);

        @Override
        public Thread newThread(Runnable r) {
            Thread thread = new Thread(r, "fluxor-tool-" + counter.incrementAndGet());
            thread.setDaemon(true);
            return thread;
        }
    }

    private final SchemaExtractor schemaExtractor;
    private final Map<String, Tool> tools = new LinkedHashMap<>();
    private final ExecutorService toolExecutor;

    /**
     * Whether this registry created (and therefore owns) the {@link #toolExecutor}.
     * When {@code true}, {@link #shutdown()} will shut the executor down; when
     * {@code false} the caller is responsible for the executor's lifecycle.
     */
    private final boolean ownsExecutor;

    /**
     * Creates a registry with a fresh {@link SchemaExtractor} and a default dedicated
     * daemon-thread pool named {@code fluxor-tool-N}. This registry owns and will shut
     * down the pool when {@link #shutdown()} is called.
     */
    public ToolRegistry() {
        this(new SchemaExtractor());
    }

    /**
     * Creates a registry with the supplied {@link SchemaExtractor} and a default dedicated
     * daemon-thread pool named {@code fluxor-tool-N}. This registry owns and will shut
     * down the pool when {@link #shutdown()} is called.
     *
     * @param schemaExtractor the extractor used to derive JSON schemas from tool parameters
     */
    public ToolRegistry(SchemaExtractor schemaExtractor) {
        this(schemaExtractor, Executors.newCachedThreadPool(new FluxorToolThreadFactory()), true);
    }

    /**
     * Creates a registry with an externally supplied executor. The caller retains ownership
     * of {@code toolExecutor} — {@link #shutdown()} will <em>not</em> shut it down.
     *
     * @param schemaExtractor the extractor used to derive JSON schemas from tool parameters
     * @param toolExecutor    the executor onto which argument binding and tool invocation are offloaded
     */
    public ToolRegistry(SchemaExtractor schemaExtractor, ExecutorService toolExecutor) {
        this(schemaExtractor, toolExecutor, false);
    }

    /**
     * Internal delegating constructor.
     *
     * @param schemaExtractor the extractor used to derive JSON schemas from tool parameters
     * @param toolExecutor    the executor onto which argument binding and tool invocation are offloaded
     * @param ownsExecutor    {@code true} iff this registry should shut the executor down on {@link #shutdown()}
     */
    private ToolRegistry(SchemaExtractor schemaExtractor, ExecutorService toolExecutor, boolean ownsExecutor) {
        this.schemaExtractor = schemaExtractor;
        this.toolExecutor = toolExecutor;
        this.ownsExecutor = ownsExecutor;
    }

    /** Scan {@code instance} for annotated tool methods and register them. */
    public ToolRegistry register(Object instance) {
        for (Method method : instance.getClass().getMethods()) {
            FluxorTool annotation = method.getAnnotation(FluxorTool.class);
            if (annotation == null) {
                continue;
            }
            String name = annotation.name().isEmpty() ? method.getName() : annotation.name();
            method.setAccessible(true);
            ToolSpec spec = new ToolSpec(name, annotation.description(),
                schemaExtractor.extractParameters(method.getParameters()));
            tools.put(name, new Tool(instance, method, spec));
        }
        return this;
    }

    /** Returns {@code true} if no tools have been registered yet. */
    public boolean isEmpty() {
        return tools.isEmpty();
    }

    /** Returns the {@link ToolSpec} list for all registered tools, preserving registration order. */
    public List<ToolSpec> specs() {
        List<ToolSpec> specs = new ArrayList<>(tools.size());
        for (Tool tool : tools.values()) {
            specs.add(tool.spec());
        }
        return specs;
    }

    /**
     * Dispatch a tool call asynchronously on the dedicated tool executor, returning the
     * JSON-serialized result as a {@link CompletableFuture}.
     *
     * <p>The argument-binding step and the reflective {@code method.invoke} are both
     * executed on {@link #toolExecutor} so they never block the provider's I/O threads.
     * If the tool method itself returns a {@code CompletableFuture<?>}, that future is
     * composed ({@code thenCompose}) so async tools still resolve correctly without
     * requiring an extra thread.
     *
     * <p>Error semantics:
     * <ul>
     *   <li>Unknown tool name → failed future with {@link IllegalArgumentException}.</li>
     *   <li>Argument-binding failure → failed future with the parsing exception wrapped in
     *       {@link java.util.concurrent.CompletionException}.</li>
     *   <li>{@link InvocationTargetException} → failed future with its
     *       {@linkplain Throwable#getCause() cause} (i.e., the exception thrown by the tool
     *       method) wrapped in {@link java.util.concurrent.CompletionException}.</li>
     *   <li>Other reflective exceptions → failed future with the exception wrapped in
     *       {@link java.util.concurrent.CompletionException}.</li>
     * </ul>
     *
     * <p>Callers using {@link java.util.concurrent.CompletableFuture#get()} will receive an
     * {@link java.util.concurrent.ExecutionException} whose cause is the original exception
     * (JDK unwraps one layer of {@code CompletionException} automatically). Callers using
     * {@code handle} or {@code exceptionally} see the {@code CompletionException} directly and
     * should walk {@link Throwable#getCause()} to reach the root cause.
     *
     * @param name          the registered tool name
     * @param argumentsJson the JSON object of arguments produced by the model, or {@code null}/blank for no args
     * @return a future that completes with the serialized tool result, or fails with the above errors
     */
    public CompletableFuture<String> invoke(String name, String argumentsJson) {
        Tool tool = tools.get(name);
        if (tool == null) {
            return CompletableFuture.failedFuture(new IllegalArgumentException("Unknown tool: " + name));
        }

        return CompletableFuture.supplyAsync(() -> {
            // Both argument binding and reflective invocation run on toolExecutor.
            final Object[] arguments;
            try {
                arguments = bindArguments(tool.method(), argumentsJson);
            } catch (Exception e) {
                throw new CompletionException(e);
            }

            try {
                return tool.method().invoke(tool.target(), arguments);
            } catch (InvocationTargetException e) {
                throw new CompletionException(e.getCause() != null ? e.getCause() : e);
            } catch (Exception e) {
                throw new CompletionException(e);
            }
        }, toolExecutor).thenCompose(returned -> {
            if (returned instanceof CompletableFuture<?> future) {
                // The tool method itself is async — compose to avoid nesting futures.
                @SuppressWarnings("unchecked")
                CompletableFuture<Object> cast = (CompletableFuture<Object>) future;
                return cast.thenApply(ToolRegistry::serialize);
            }
            return CompletableFuture.completedFuture(serialize(returned));
        });
    }

    /**
     * Shuts down the tool executor if this registry owns it (i.e., it was created by this
     * registry rather than injected from outside). Safe to call multiple times.
     */
    public void shutdown() {
        if (ownsExecutor) {
            toolExecutor.shutdown();
        }
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private Object[] bindArguments(Method method, String argumentsJson) throws Exception {
        JsonNode root = (argumentsJson == null || argumentsJson.isBlank())
            ? Json.MAPPER.createObjectNode()
            : Json.MAPPER.readTree(argumentsJson);

        Parameter[] parameters = method.getParameters();
        Object[] arguments = new Object[parameters.length];
        for (int i = 0; i < parameters.length; i++) {
            Parameter parameter = parameters[i];
            JsonNode value = root.get(parameter.getName());
            if (value == null || value.isNull()) {
                arguments[i] = null;
                continue;
            }
            JavaType target = Json.MAPPER.getTypeFactory().constructType(parameter.getParameterizedType());
            arguments[i] = Json.MAPPER.convertValue(value, target);
        }
        return arguments;
    }

    private static String serialize(Object value) {
        if (value == null) {
            return "null";
        }
        if (value instanceof String s) {
            return s; // pass strings through unquoted for readability in the tool message
        }
        try {
            return Json.MAPPER.writeValueAsString(value);
        } catch (Exception e) {
            return String.valueOf(value);
        }
    }

    private record Tool(Object target, Method method, ToolSpec spec) {
    }
}
