/**
 * Writes `pf:compare`'s markdown table into the "## Resultados" section of
 * `docs/pf-context-mode-campaign.md` (Step P3/P4) — the rest of that document
 * (suites chosen, checklist, exact command) is authored by P4 and must never
 * be touched by this tool: "el comparador añade su sección, NO pisa el
 * resto." Idempotent: running `pf:compare` again replaces only this section
 * with a fresh render, wherever it currently sits in the document.
 */
import { readFile, writeFile } from 'fs/promises';

export const RESULTS_SECTION_HEADING = '## Resultados';

/**
 * Inserts or replaces the `RESULTS_SECTION_HEADING` section of the markdown
 * document at `docPath`, leaving every other section untouched.
 *
 * - If the heading doesn't exist yet, the section is appended at the end.
 * - If it exists, everything from that heading up to (but not including) the
 *   next level-1/level-2 heading — or EOF — is replaced.
 * - If the file doesn't exist at all, it is created containing just this
 *   section (defensive: P4 is expected to have authored the rest first, but
 *   this keeps the tool usable standalone).
 */
export async function upsertResultsSection(docPath: string, markdownTable: string): Promise<void> {
  let existing = '';
  try {
    existing = await readFile(docPath, 'utf-8');
  } catch (error: unknown) {
    const code = (error as NodeJS.ErrnoException)?.code;
    if (code !== 'ENOENT') throw error;
  }

  const section = [
    RESULTS_SECTION_HEADING,
    '',
    '_Generated by `pf:compare` — do not hand-edit; re-run the command to refresh._',
    '',
    markdownTable.trimEnd(),
  ].join('\n');

  const next = replaceOrAppendSection(existing, section);
  await writeFile(docPath, next, 'utf-8');
}

function replaceOrAppendSection(existing: string, section: string): string {
  const trimmedExisting = existing.replace(/\s+$/, '');

  if (trimmedExisting.length === 0) {
    return `${section}\n`;
  }

  const lines = trimmedExisting.split('\n');
  const headingIndex = lines.findIndex((line) => line.trim() === RESULTS_SECTION_HEADING);

  if (headingIndex === -1) {
    return `${trimmedExisting}\n\n${section}\n`;
  }

  // The section runs until the next level-1/level-2 heading, or EOF.
  let endIndex = lines.length;
  for (let i = headingIndex + 1; i < lines.length; i++) {
    if (/^#{1,2}\s/.test(lines[i])) {
      endIndex = i;
      break;
    }
  }

  const before = lines.slice(0, headingIndex).join('\n').replace(/\s+$/, '');
  const after = lines.slice(endIndex).join('\n').replace(/^\s+/, '');

  const parts = [before, section, after].filter((part) => part.length > 0);
  return `${parts.join('\n\n')}\n`;
}
