package io.heliox.sdk.tool;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonNode;
import io.heliox.sdk.internal.Json;
import io.heliox.sdk.provider.ToolSpec;
import io.heliox.sdk.schema.SchemaExtractor;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Scans Java objects for {@link HelioxTool}-annotated methods and exposes them to the
 * runtime. Parameter schemas are generated by reusing {@link SchemaExtractor}; a call is
 * dispatched by binding the model's JSON arguments back to the method parameters (by name)
 * and invoking it reflectively.
 *
 * <p>Tool methods may return any value (serialized to JSON) or a {@link CompletableFuture}
 * (awaited and then serialized), keeping the whole pipeline non-blocking.
 */
public final class ToolRegistry {

    private final SchemaExtractor schemaExtractor;
    private final Map<String, Tool> tools = new LinkedHashMap<>();

    public ToolRegistry() {
        this(new SchemaExtractor());
    }

    public ToolRegistry(SchemaExtractor schemaExtractor) {
        this.schemaExtractor = schemaExtractor;
    }

    /** Scan {@code instance} for annotated tool methods and register them. */
    public ToolRegistry register(Object instance) {
        for (Method method : instance.getClass().getMethods()) {
            HelioxTool annotation = method.getAnnotation(HelioxTool.class);
            if (annotation == null) {
                continue;
            }
            String name = annotation.name().isEmpty() ? method.getName() : annotation.name();
            method.setAccessible(true);
            ToolSpec spec = new ToolSpec(name, annotation.description(),
                schemaExtractor.extractParameters(method.getParameters()));
            tools.put(name, new Tool(instance, method, spec));
        }
        return this;
    }

    public boolean isEmpty() {
        return tools.isEmpty();
    }

    public List<ToolSpec> specs() {
        List<ToolSpec> specs = new ArrayList<>(tools.size());
        for (Tool tool : tools.values()) {
            specs.add(tool.spec());
        }
        return specs;
    }

    /** Dispatch a tool call, returning the JSON-serialized result. */
    public CompletableFuture<String> invoke(String name, String argumentsJson) {
        Tool tool = tools.get(name);
        if (tool == null) {
            return CompletableFuture.failedFuture(new IllegalArgumentException("Unknown tool: " + name));
        }

        final Object[] arguments;
        try {
            arguments = bindArguments(tool.method(), argumentsJson);
        } catch (Exception e) {
            return CompletableFuture.failedFuture(e);
        }

        try {
            Object returned = tool.method().invoke(tool.target(), arguments);
            if (returned instanceof CompletableFuture<?> future) {
                return future.thenApply(ToolRegistry::serialize);
            }
            return CompletableFuture.completedFuture(serialize(returned));
        } catch (InvocationTargetException e) {
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            return CompletableFuture.failedFuture(cause);
        } catch (Exception e) {
            return CompletableFuture.failedFuture(e);
        }
    }

    private Object[] bindArguments(Method method, String argumentsJson) throws Exception {
        JsonNode root = (argumentsJson == null || argumentsJson.isBlank())
            ? Json.MAPPER.createObjectNode()
            : Json.MAPPER.readTree(argumentsJson);

        Parameter[] parameters = method.getParameters();
        Object[] arguments = new Object[parameters.length];
        for (int i = 0; i < parameters.length; i++) {
            Parameter parameter = parameters[i];
            JsonNode value = root.get(parameter.getName());
            if (value == null || value.isNull()) {
                arguments[i] = null;
                continue;
            }
            JavaType target = Json.MAPPER.getTypeFactory().constructType(parameter.getParameterizedType());
            arguments[i] = Json.MAPPER.convertValue(value, target);
        }
        return arguments;
    }

    private static String serialize(Object value) {
        if (value == null) {
            return "null";
        }
        if (value instanceof String s) {
            return s; // pass strings through unquoted for readability in the tool message
        }
        try {
            return Json.MAPPER.writeValueAsString(value);
        } catch (Exception e) {
            return String.valueOf(value);
        }
    }

    private record Tool(Object target, Method method, ToolSpec spec) {
    }
}
